author: 황성현
title: 황성현
email: me@sunghyunzz.com
description: 황성현이 가끔 나타나 방귀도 뀌고 트림도 하다 가는 곳
baseurl: ""
url: "https://hwang.sh"

profiles:
  - name: Twitter
    url: https://twitter.com/_sunghyunzz
  - name: Github
    url: https://github.com/sunghyunzz
  - name: Letterboxd
    url: https://letterboxd.com/sunghyunzz

sass:
  sass_dir: css
  style: compressed

permalink: /posts/:year/:month/:day/:title.html

asset_url: /assets

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - Makefile
  - CNAME
  - .gitignore
